name: TheDropper
main: TheDropper\Main
api: 3.0.0, 4.0.0
version: 1.0.0

commands:
    td:
        usage: "/td <addarena/regsign> <worldname> <amount/[line3]> [line4]"
        description: "Dropper command"
        permission: dropper.command

permissions:
    dropper.command:
        default: op
        description: "Dropper command permission"
